<?php

namespace Database\Seeders;

use App\Models\Buku;
use Illuminate\Database\Seeder;

class BukuSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'isbn'            => '978-979-461-487-1',
                'judul'           => 'Perempuan di Titik Nol',
                'edisi'           => '1',
                'deskripsi_fisik' => '156 hlm; 20 cm',
                'bahasa'          => 'Indonesia',
                'cover'           => 'covers/perempuan-di-titik-nol.webp',
                'tersedia'        => true,
                'id_jenis'        => 'JNS-005',
                'penulis'         => 'Nawal el-Saadawi',
                'penerbit'        => 'Yayasan Pustaka Obor',
            ],
            [
                'isbn'            => '978-602-03-2478-3',
                'judul'           => 'The Alchemist',
                'edisi'           => '1',
                'deskripsi_fisik' => '224 hlm; 20 cm',
                'bahasa'          => 'Indonesia',
                'cover'           => 'covers/the-alchemist.webp',
                'tersedia'        => true,
                'id_jenis'        => 'JNS-005',
                'penulis'         => 'Paulo Coelho',
                'penerbit'        => 'Gramedia',
            ],
            [
                'isbn'            => '978-602-06-3317-6',
                'judul'           => 'Atomic Habits',
                'edisi'           => '1',
                'deskripsi_fisik' => '352 hlm; 23 cm',
                'bahasa'          => 'Indonesia',
                'cover'           => 'covers/atomic-habits.webp',
                'tersedia'        => true,
                'id_jenis'        => 'JNS-007',
                'penulis'         => 'James Clear',
                'penerbit'        => 'Gramedia',
            ],
            [
                'isbn'            => '978-602-03-1157-8',
                'judul'           => 'Supernova: Ksatria, Puteri, dan Bintang Jatuh',
                'edisi'           => '1',
                'deskripsi_fisik' => '344 hlm; 20 cm',
                'bahasa'          => 'Indonesia',
                'cover'           => 'covers/supernova.webp',
                'tersedia'        => true,
                'id_jenis'        => 'JNS-005',
                'penulis'         => 'Dee Lestari',
                'penerbit'        => 'Gramedia',
            ],
            [
                'isbn'            => '978-602-8811-55-2',
                'judul'           => 'Bumi',
                'edisi'           => '1',
                'deskripsi_fisik' => '440 hlm; 20 cm',
                'bahasa'          => 'Indonesia',
                'cover'           => 'covers/bumi.webp',
                'tersedia'        => true,
                'id_jenis'        => 'JNS-005',
                'penulis'         => 'Tere Liye',
                'penerbit'        => 'Gramedia',
            ],
            [
                'isbn'            => '978-602-06-3318-3',
                'judul'           => 'Bulan',
                'edisi'           => '1',
                'deskripsi_fisik' => '400 hlm; 20 cm',
                'bahasa'          => 'Indonesia',
                'cover'           => 'covers/bulan.webp',
                'tersedia'        => true,
                'id_jenis'        => 'JNS-005',
                'penulis'         => 'Tere Liye',
                'penerbit'        => 'Gramedia',
            ],
            [
                'isbn'            => '978-602-03-3295-5',
                'judul'           => 'Hujan',
                'edisi'           => '1',
                'deskripsi_fisik' => '320 hlm; 20 cm',
                'bahasa'          => 'Indonesia',
                'cover'           => 'covers/hujan.webp',
                'tersedia'        => true,
                'id_jenis'        => 'JNS-005',
                'penulis'         => 'Tere Liye',
                'penerbit'        => 'Gramedia',
            ],
            [
                'isbn'            => '978-602-03-8591-3',
                'judul'           => 'Normal People',
                'edisi'           => '1',
                'deskripsi_fisik' => '288 hlm; 20 cm',
                'bahasa'          => 'Inggris',
                'cover'           => 'covers/normal-people.webp',
                'tersedia'        => true,
                'id_jenis'        => 'JNS-005',
                'penulis'         => 'Sally Rooney',
                'penerbit'        => 'Faber & Faber',
            ],
            [
                'isbn'            => '978-979-22-9224-7',
                'judul'           => 'Laskar Pelangi',
                'edisi'           => '1',
                'deskripsi_fisik' => '529 hlm; 21 cm',
                'bahasa'          => 'Indonesia',
                'cover'           => 'covers/laskar-pelangi.webp',
                'tersedia'        => true,
                'id_jenis'        => 'JNS-005',
                'penulis'         => 'Andrea Hirata',
                'penerbit'        => 'Gramedia',
            ],
            [
                'isbn'            => '978-979-91-0224-8',
                'judul'           => 'Bumi Manusia',
                'edisi'           => '1',
                'deskripsi_fisik' => '535 hlm; 21 cm',
                'bahasa'          => 'Indonesia',
                'cover'           => 'covers/bumi-manusia.webp',
                'tersedia'        => true,
                'id_jenis'        => 'JNS-008',
                'penulis'         => 'Pramoedya Ananta Toer',
                'penerbit'        => 'Yayasan Pustaka Obor',
            ],
            [
                'isbn'            => '978-979-433-397-2',
                'judul'           => 'Tuesdays with Morrie',
                'edisi'           => '1',
                'deskripsi_fisik' => '208 hlm; 20 cm',
                'bahasa'          => 'Indonesia',
                'cover'           => 'covers/tuesdays-with-morrie.webp',
                'tersedia'        => true,
                'id_jenis'        => 'JNS-007',
                'penulis'         => 'Mitch Albom',
                'penerbit'        => 'Gramedia',
            ],
            [
                'isbn'            => '978-006-112-241-5',
                'judul'           => 'The Diary of a Young Girl',
                'edisi'           => 'Definitive',
                'deskripsi_fisik' => '368 hlm; 19 cm',
                'bahasa'          => 'Inggris',
                'cover'           => 'covers/the-diary-of-a-young-girl.webp',
                'tersedia'        => true,
                'id_jenis'        => 'JNS-008',
                'penulis'         => 'Anne Frank',
                'penerbit'        => 'HarperOne',
            ],
        ];

        foreach ($data as $item) {
            Buku::firstOrCreate(['isbn' => $item['isbn']], $item);
        }
    }
}
